lol-clash:
    data:
        simpleStateFlagIds:
        - "registration_open_tournament_3162"
        - "registration_open_tournament_3762"
        - "lock_in_open_tournament_3762_phase_3882"
        - "registration_open_tournament_3789"
        - "lock_in_open_tournament_3789_phase_3909"
        - "registration_open_tournament_27461"
    schemaVersion: 1
lol-home:
    data:
        useTFTOverride: false
    schemaVersion: 0
lol-premade-voice:
    data:
        currentCaptureDeviceHandle: "Default System Device"
        inputVolume: 50
        vadSensitivity: 65
    schemaVersion: 1
lol-replays:
    data:
        dontShowEogUsageTip: true
    schemaVersion: 1
lol-user-experience:
    data:
        hasBeenPromptedForPotatoMode: true
        lastKnownMachineSpec: 5
        potatoModeEnabled: true
    schemaVersion: 3
video:
    data:
        ZoomScale: 1
    schemaVersion: 1
