page-settings:
    data:
        pages: []
        perShardPerkBooks:
            eun1:
                currentPageId: 953382
                pages:
                -   autoModifiedSelections: []
                    current: false
                    id: 1998404863
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: false
                    lastModified: 1642693868328
                    name: "New Runes Page 1"
                    order: 0
                    primaryStyleId: 8200
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    - -1
                    subStyleId: -1
                -   autoModifiedSelections: []
                    current: false
                    id: 1863777362
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: true
                    lastModified: 1644267886848
                    name: "New Runes Page 2asdasda"
                    order: 1
                    primaryStyleId: 8000
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - 8010
                    - 9111
                    - 9105
                    - 8014
                    - 8473
                    - 8453
                    - 5008
                    - 5008
                    - 5002
                    subStyleId: 8400
                -   autoModifiedSelections: []
                    current: false
                    id: 1154617539
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: true
                    lastModified: 1664661975111
                    name: "Porofessor: Graves - Master+"
                    order: 2
                    primaryStyleId: 8000
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - 8021
                    - 8009
                    - 9104
                    - 8014
                    - 8304
                    - 8345
                    - 5005
                    - 5008
                    - 5003
                    subStyleId: 8300
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: true
            showLongDescriptions: false
            showPresetPages: true
    schemaVersion: 5
